import { StyleSheet } from "react-native";

export default StyleSheet.create({
  h1: {
    fontSize: 40,
    color: "#fff",
    fontFamily: "Nunito_300Light",
    flexShrink: 1,
  },
  h2: {
    fontSize: 30,
    color: "#fff",
    fontFamily: "Nunito_300Light",
    flexShrink: 1,
  },
  h3: {
    fontSize: 25,
    color: "#000",
    fontFamily: "Nunito_300Light",
    flexShrink: 1,
  },
  h3bold: {
    fontSize: 25,
    color: "#BB79BD",
    fontFamily: "Nunito_300Light",
    flexShrink: 1,
    fontWeight: "bold",
  },
  h4: {
    fontSize: 20,
    color: "#000",
    fontFamily: "Nunito_300Light",
    flexShrink: 1,
  },
  h4white: {
    fontSize: 20,
    color: "#fff",
    fontFamily: "Nunito_300Light",
    flexShrink: 1,
  },
  h4bold: {
    fontSize: 20,
    color: "#459ECF",
    fontFamily: "Nunito_300Light",
    flexShrink: 1,
    fontWeight: "bold",
  },

  horizontal: {
    flexDirection: "row",
    flex: 0.5,
    justifyContent: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  textContainer: {
    width: "85%",
    margin: 10,
  },
  headerContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 90,
    margin: 10,
  },
  headerContainer2: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    margin: 10,
  },
  button: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: "#fff",
    borderRadius: 10,
    width: "65%",
    height: 50,
  },
  buttonPink: {
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
    backgroundColor: "#BB79BD",
    borderRadius: 10,
    width: "65%",
    height: 50,
  },
  buttonBlue: {
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
    backgroundColor: "#459ECF",
    borderRadius: 10,
    width: "55%",
    height: 50,
  },
  buttonClear: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#000",
    borderRadius: 10,
    width: "30%",
    height: 50,
  },
  buttonGame: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 3,
    borderColor: "#459ECF",
    borderRadius: 5,
    margin: 2,
    width: "90%",
    height: 60,
  },
  text: {
    fontSize: 18,
    color: "#000",
    fontFamily: "Nunito_300Light",
  },
  input: {
    padding: 5,
    marginTop: 5,
    marginBottom: 5,
    width: "70%",
    height: 30,
    borderBottomColor: "#000",
    borderBottomWidth: 2,
    fontFamily: "Nunito_300Light",
  },
});
